version: "3.3"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - my-dbvolume:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
    expose:
      - 3306
volumes:
  my-dbvolume:
    driver: local

  # web:
  #   image: nginx:latest
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - db
